model:
  name: sasrec
  save_name: sasrec_CE

  params:
    model_params:
      block_count: 1
      head_count: 1
      max_seq_len: 100
      hidden_size: 128
      dropout_rate: 0.35
      loss_type: CE # CE, BCE, SCE
      loss_sample_count: 200
      n_buckets: 443
      bucket_size_x: 443
      bucket_size_y: 512
      mix_x: true
    training_params:
      embedding_dim: 128
      learning_rate: 0.0003
      weight_decay: 0.01
      batch_size: 256
      num_workers: 4
      patience: 4
      max_epochs: 20
      precision: 16-mixed #default 32, bf16-mixed
