model:
  name: sasrec
  save_name: sasrec_CE

  params:
    model_params:
      block_count: 4
      head_count: 2
      max_seq_len: 100
      hidden_size: 384
      dropout_rate: 0.1
      loss_type: CE # CE, BCE, SCE
      loss_sample_count: [10, 100, 300, 500, 1000, 5000] #List of samples for experiment with metric convergence
    training_params:
      embedding_dim: 300
      learning_rate: 0.001
      batch_size: 32
      num_workers: 4
      patience: 10
      max_epochs: 2
      precision: null #default 32, bf16-mixed
      number_launches: 3 #Number of experiments for each loass sample count
