model:
  name: sasrec
  save_name: sasrec_ARCFACE

  params:
    model_params:
      block_count: 2
      head_count: 2
      max_seq_len: 100
      hidden_size: 256
      dropout_rate: 0.15
      loss_type: ARCFACE # CE, BCE, SCE, ARCFACE, ALTCE
      loss_sample_count: 500
      margin: 5.0 #parameter for ARCFACE loss function
      scale: 1.0 #parameter for ARCFACE loss function
      n_buckets: 443
      bucket_size_x: 443
      bucket_size_y: 512
      mix_x: true
    training_params:
      embedding_dim: 256
      learning_rate: 0.001
      batch_size: 32
      num_workers: 4
      patience: 10
      max_epochs: 10
      precision: null #default 32, bf16-mixed