#! /bin/bash

DOCKER_NAME="fast_recsys" # username in container
CONTAINER_NAME=$USER"-fastrc" # name of container
SRC="fastrecsys/RePlay-Accelerated/" # source directory (supposedly, this repo's path is /home/${USER}/${SRC})

# to get these values type "id" in shell termilal
DOCKER_USER_ID=$(id -u) 
DOCKER_GROUP_ID=$(id -g)