defaults:
  - dataset: movielens
  - model: sasrec
  - mode: train
  - acceleration: null
  - _self_

env:
  CUDA_DEVICE_ORDER: "PCI_BUS_ID" 
  OMP_NUM_THREADS: "4"
  CUDA_VISIBLE_DEVICES: "0"

paths:
  data_dir: "replay_benchmarks/data/"
  model_dir: "replay_benchmarks/artifacts/models/"
  log_dir: "replay_benchmarks/artifacts/logs/"
  checkpoint_dir: "replay_benchmarks/artifacts/checkpoints/"
  results_dir: "replay_benchmarks/artifacts/results/"