defaults:
  - dataset: movielens_1m
  - model: sasrec_movielens_1m
  - mode: hyperparameter_experiment
  - acceleration: null

env:
  SEED: 42
  CUDA_DEVICE_ORDER: "PCI_BUS_ID" 
  OMP_NUM_THREADS: "4"
  CUDA_VISIBLE_DEVICES: "0"

paths:
  data_dir: "replay_benchmarks/data/"
  log_dir: "replay_benchmarks/artifacts/logs/"
  checkpoint_dir: "replay_benchmarks/artifacts/checkpoints/"
  results_dir: "replay_benchmarks/artifacts/results/"
  main_csv_res_dir: "replay_benchmarks/artifacts"

metrics:
  types:
    - ndcg
    - recall
    - hitrate
    - precision
    - map
    - mrr
  ks:
    - 1
    - 5
    - 10
    - 20
    - 100