mode:
  name: hyperparameter_experiment

  max_seq_len: [32, 64, 128, 256, 512, 1024]
  loss_type: CE
  loss_sample_count: [1, 128, 256, 512, 1024]
  bucket_size_y: [64, 256, 1024, 2048]
  batch_size: [16, 32, 64]
  number_launches: 1


